# Generated by Django 4.2.16 on 2026-04-18 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGIN_OTP_SENT', 'OTP enviado'), ('LOGOUT', 'Cierre de sesión'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('CHAT_QUERY', 'Consulta al chatbot'), ('CHAT_VOICE_QUERY', 'Consulta de voz al chatbot'), ('DATA_ACCESS_GRADES', 'Acceso a notas'), ('DATA_ACCESS_SCHEDULE', 'Acceso a horarios'), ('DATA_ACCESS_PROFILE', 'Acceso a perfil académico'), ('RAG_QUERY', 'Consulta al índice RAG'), ('RAG_INDEX_BUILD', 'Construcción del índice RAG'), ('SYSTEM_ERROR', 'Error del sistema')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento (JSON)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
