# Generated by Django 4.2.16 on 2026-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGIN_OTP_SENT', 'OTP enviado'), ('LOGOUT', 'Cierre de sesión'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('CHAT_QUERY', 'Consulta al chatbot'), ('CHAT_VOICE_QUERY', 'Consulta de voz al chatbot'), ('DATA_ACCESS_GRADES', 'Acceso a notas'), ('DATA_ACCESS_SCHEDULE', 'Acceso a horarios'), ('DATA_ACCESS_PROFILE', 'Acceso a perfil académico'), ('DATA_ACCESS_STATS', 'Acceso a estadísticas académicas'), ('DATA_ACCESS_ACTIVITIES', 'Acceso a actividades'), ('DATA_ACCESS_NOTIFICATIONS', 'Acceso a notificaciones'), ('DATA_SUBMIT_ACTIVITY', 'Entrega de actividad'), ('TEACHER_CREATE_ACTIVITY', 'Creación de actividad docente'), ('RAG_QUERY', 'Consulta al índice RAG'), ('RAG_INDEX_BUILD', 'Construcción del índice RAG'), ('SYSTEM_ERROR', 'Error del sistema')], max_length=50),
        ),
    ]
