# Generated by Django 4.2.16 on 2026-04-18 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ej: A-101', max_length=10, unique=True)),
                ('building', models.CharField(choices=[('A', 'Edificio A'), ('B', 'Edificio B'), ('C', 'Edificio C'), ('LAB', 'Laboratorios'), ('AUD', 'Auditorio')], max_length=3)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('is_lab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'classroom',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'professor',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField(default=4)),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('carrera', models.CharField(choices=[('IDS', 'Ingeniería en Desarrollo de Software'), ('ADM', 'Administración de Empresas'), ('AGR', 'Agronomía'), ('ZOO', 'Zootecnia'), ('VET', 'Medicina Veterinaria'), ('ENF', 'Enfermería'), ('DER', 'Derecho'), ('ARQ', 'Arquitectura'), ('NEG', 'Negocios Internacionales'), ('GAS', 'Gastronomía'), ('DIS', 'Diseño Gráfico'), ('AUD', 'Auditoría y Gestión Contable'), ('CIV', 'Ingeniería Civil'), ('PED', 'Pedagogía de los Idiomas')], default='IDS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'subject',
                'ordering': ['carrera', 'semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(help_text='ej: EST-001', max_length=20, unique=True)),
                ('carrera', models.CharField(choices=[('IDS', 'Ingeniería en Desarrollo de Software'), ('ADM', 'Administración de Empresas'), ('AGR', 'Agronomía'), ('ZOO', 'Zootecnia'), ('VET', 'Medicina Veterinaria'), ('ENF', 'Enfermería'), ('DER', 'Derecho'), ('ARQ', 'Arquitectura'), ('NEG', 'Negocios Internacionales'), ('GAS', 'Gastronomía'), ('DIS', 'Diseño Gráfico'), ('AUD', 'Auditoría y Gestión Contable'), ('CIV', 'Ingeniería Civil'), ('PED', 'Pedagogía de los Idiomas')], default='IDS', max_length=3)),
                ('semester_current', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('career_start_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'student',
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_period', models.CharField(help_text='ej: 2024-2025-II', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.classroom')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.professor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.subject')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_period', models.CharField(max_length=20)),
                ('partial_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('partial_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('partial_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('approved', 'Aprobado'), ('failed', 'Reprobado'), ('pending', 'En curso')], default='pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.subject')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'grade',
                'indexes': [models.Index(fields=['student', 'academic_period'], name='grade_student_ec58c5_idx')],
                'unique_together': {('student', 'subject', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_period', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado'), ('completed', 'Completado')], default='active', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'enrollment',
                'unique_together': {('student', 'schedule', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=10)),
                ('message', models.TextField()),
                ('context_used', models.JSONField(blank=True, default=dict, help_text='Fragmentos RAG y datos DB usados para esta respuesta')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='students.student')),
            ],
            options={
                'verbose_name': 'Historial de Conversación',
                'verbose_name_plural': 'Historiales de Conversación',
                'db_table': 'conversation_history',
                'ordering': ['session_id', 'timestamp'],
                'indexes': [models.Index(fields=['student', 'session_id'], name='conversatio_student_243d78_idx'), models.Index(fields=['student', 'timestamp'], name='conversatio_student_22d823_idx')],
            },
        ),
    ]
