# Generated by Django 4.2.16 on 2026-04-18 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_grade_final_exam_alter_grade_final_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de asistencia (mínimo 80% para aprobar)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
