# Generated by Django 4.2.16 on 2026-05-22 23:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_grade_attendance_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(choices=[('IDS', 'Ingeniería en Desarrollo de Software'), ('ITI', 'Ingeniería en Tecnologías de la Información'), ('ADM', 'Administración de Empresas'), ('AGR', 'Agronomía'), ('ZOO', 'Zootecnia'), ('VET', 'Medicina Veterinaria'), ('ENF', 'Enfermería'), ('DER', 'Derecho'), ('ARQ', 'Arquitectura'), ('NEG', 'Negocios Internacionales'), ('GAS', 'Gastronomía'), ('DIS', 'Diseño Gráfico'), ('AUD', 'Auditoría y Gestión Contable'), ('CIV', 'Ingeniería Civil'), ('IAM', 'Ingeniería Ambiental'), ('PED', 'Pedagogía de los Idiomas')], default='IDS', max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='carrera',
            field=models.CharField(choices=[('IDS', 'Ingeniería en Desarrollo de Software'), ('ITI', 'Ingeniería en Tecnologías de la Información'), ('ADM', 'Administración de Empresas'), ('AGR', 'Agronomía'), ('ZOO', 'Zootecnia'), ('VET', 'Medicina Veterinaria'), ('ENF', 'Enfermería'), ('DER', 'Derecho'), ('ARQ', 'Arquitectura'), ('NEG', 'Negocios Internacionales'), ('GAS', 'Gastronomía'), ('DIS', 'Diseño Gráfico'), ('AUD', 'Auditoría y Gestión Contable'), ('CIV', 'Ingeniería Civil'), ('IAM', 'Ingeniería Ambiental'), ('PED', 'Pedagogía de los Idiomas')], default='IDS', max_length=3),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('file', models.FileField(blank=True, null=True, upload_to='activities/instructions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.subject')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activity',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='activities/submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'activity_submission',
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
